### ISSUE TITLE
[CI/CD] Add cache for build olmlib step

### ISSUE THREAD

**Issue by drminh2807** [linagora/twake-on-matrix#673]
- `Build olmlib` step take 4-5 minutes for every build
- Add cache to decrease the build time
- I think no need `flutter clean` it can take time. action in tests.yaml still can build success without it
![Screenshot 2023-09-25 at 14 31 13](https://github.com/linagora/twake-on-matrix/assets/12546908/2bb2a08e-5cfa-4602-a379-bb6e15f7c34d)

**Comment by hoangdat** [comment]
Hi @tk-nguyen, what do you think about this?

**Comment by tk-nguyen** [comment]
I've experimented with caching nix build, but it seems to provide little to no time improvement: https://github.com/tk-nguyen/twake-on-matrix/pull/4. So I've decided to not persue it further.

![image](https://github.com/linagora/twake-on-matrix/assets/39090621/0df82009-d5e6-4e55-aa26-f7c196fa2731)


On running `flutter clean`, you can remove it from our build `scripts`, see if the tests + builds run fine.

**Comment by drminh2807** [comment]
@tk-nguyen  it is not correct
you should cache the output of libolm build
```
    - name: Cache libolm
      id: cache-libolm
      uses: actions/cache@v3
      with:
        path: assets/js
        key: ${{ runner.os }}-$LIBOLM_VERSION-libolm

    - name: Build libolm
      if: steps.cache-libolm.outputs.cache-hit != 'true'
      run: ...
```
